Fix mesos.Credential.secret type mismatch
An Jan.16 2016 update of mesos/mesos-go changes type of
mesos.Credential.secret from bytes to string.

    https://github.com/mesos/mesos-go/commit/7870a46fd9ad7d9d47dc518c46750c969c602bde#diff-8b984a6759078d3bd0e4a27e90ab541dR1239

This results a type mismatch at scheduler/init.go:50. Error
message below

    cannot use secret (type []byte) as type *string in field value

This patch fixes it by converting `secret` from []byte to string
before passing it to mesos.Credential.